"""Add relationships between Product, Reservation, and Order

Revision ID: 6aa0a9bfcc88
Revises: 2c26aaeef71c
Create Date: 2025-04-20 14:48:54.503711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa0a9bfcc88'
down_revision: Union[str, None] = '2c26aaeef71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
